linters:
  RuboCop:
    ignored_cops:
      - Style/NestedTernaryOperator
      - Style/TrailingBlankLines

  LineLength:
    enabled: false
  RuboCop:
    exclude:
      - app/views/kaminari/_page.html.haml
