language: ruby
rvm:
  - 2.2.0

addons:
  postgresql: "9.3"
  code_climate:
    repo_token: 024f95ec0563c35d69be6daa57c3cd415c57c55ae532f7590529cf3819c4e13d
before_script:
  - psql -c 'create database draconomicon_test;' -U postgres
env:
  - RAILS_ENV=test RACK_TIMEOUT=30
notifications:
  email:
    recipients:
      - gryphon92@gmail.com
    on_success: change
    on_failure: always
script:
  - bundle exec rake db:schema:load
  - bundle exec rake spec
