default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password:

development:
  <<: *default
  database: the-draconomicon_development

test:
  <<: *default
  database: the-draconomicon_test
