# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  airbrake_api_key: <%= ENV["AIRBRAKE_API_KEY"] %>
  devise_secret_key: FAKE_DEVISE_KEY
  secret_key_base: FAKE_SECRET_KEY

test:
  airbrake_api_key: <%= ENV["AIRBRAKE_API_KEY"] %>
  devise_secret_key: FAKE_DEVISE_KEY
  secret_key_base: FAKE_SECRET_KEY

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  airbrake_api_key: <%= ENV["AIRBRAKE_API_KEY"] %>
  devise_secret_key: <%= ENV["DEVISE_SECRET_KEY"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  sendgrid_password: <%= ENV["SENDGRID_PASSWORD"] %>
  sendgrid_username: <%= ENV["SENDGRID_USERNAME"] %>
