# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e2b3124a5a72f12549ee5faf03946a1ffdf4bbfe277c33d4ef07d1a24411e6b7b0e8d118181989e4aa6a1c53ccbefb37677d1f7981897d43f9f6f85a990926df
  devise_secret_key: FAKE_DEVISE_KEY

test:
  secret_key_base: 1c51cef492c1545116235a4118f03c7c184aad8950112da4daf2e75077d139ae994a2c892a1dcb5322069264b77c761b081d19320e3533ee5e28145805f9abac
  devise_secret_key: FAKE_DEVISE_KEY

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  devise_secret_key: <%= ENV["DEVISE_SECRET_KEY"] %>
  sendgrid_username: <%= ENV["SENDGRID_USERNAME"] %>
  sendgrid_password: <%= ENV["SENDGRID_PASSWORD"] %>
